[workspace.package]
version = "0.1.0"
authors = [
    "Thomas Lamprecht <t.lamprecht@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox-datacenter-manager.git"

exclude = [ "build" ]

[workspace]
members = [
    "api",
    "api/pdm-buildcfg",
    "api/pdm-api-types",
    "api/pdm-config",
    "api/pdm-ticket",
]

[workspace.dependencies]
# proxmox workspace
proxmox-lang = "1.1"
proxmox-rest-server = "0.2.1"
# some use "cli", some use "cli" and "server", pbs-config uses nothing
proxmox-router = { version = "1.3.1", default_features = false }
# everything but pbs-config and pbs-client ues "api-macro"
proxmox-schema = "1.3.6"
proxmox-serde = "0.1.1"
proxmox-time = "1.1.2"
proxmox-uuid = "1"

# PDM workspace
pdm-api-types = { path = "api/pdm-api-types" }
pdm-buildcfg = { path = "api/pdm-buildcfg" }
pdm-config = { path = "api/pdm-config" }
# TODO: move this+PBS ones out to a e.g. proxmox-auth-ticket crate
pdm-ticket = { path = "api/pdm-ticket" }

# regular crates
anyhow = "1.0"
base64 = "0.13"
hex = "0.4.3"
http = "0.2"
hyper = { version = "0.14", features = [ "full" ] }
lazy_static = "1.4"
openssl = "0.10.40"
percent-encoding = "2.1"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "1"
tokio = "1.6"
