[workspace.package]
version = "0.1.0"
authors = [
    "Thomas Lamprecht <t.lamprecht@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox-datacenter-manager.git"

exclude = [ "build" ]

[workspace]
members = [
    "api",
    "api/pdm-buildcfg",
    "api/pdm-api-types",
    "api/pdm-config",
    "api/pdm-ticket",
]

[workspace.dependencies]
# proxmox workspace
proxmox-async = "0.4"
proxmox-http = { version = "0.8", features = [ "client", "http-helpers", "websocket" ] } # see below
proxmox-io = "1.0.1" # tools and client use "tokio" feature
proxmox-lang = "1.1"
#proxmox-metrics = "0.2"
proxmox-rest-server = "0.3"
# some use "cli", some use "cli" and "server", pbs-config uses nothing
proxmox-router = { version = "1.3.1", default_features = false }
# everything but pbs-config and pbs-client ues "api-macro"
proxmox-schema = "1.3.6"
proxmox-section-config = "1"
proxmox-serde = "0.1.1"
proxmox-shared-memory = "0.2.3"
proxmox-sortable-macro = "0.1.2"
proxmox-subscription = { version = "0.3", features = [ "api-types" ] }
proxmox-sys = "0.4.2"
proxmox-tfa = { version = "3.0", features = [ "api", "api-types" ] }
proxmox-time = "1.1.2"
proxmox-uuid = "1"

# other proxmox crates
proxmox-acme-rs = "0.4"
proxmox-apt = "0.9.0"
proxmox-openid = "0.9.8"

# PDM workspace
pdm-api-types = { path = "api/pdm-api-types" }
pdm-buildcfg = { path = "api/pdm-buildcfg" }
pdm-config = { path = "api/pdm-config" }
# TODO: move this+PBS ones out to a e.g. proxmox-auth-ticket crate
pdm-ticket = { path = "api/pdm-ticket" }
#pdm-client = { path = "pdm-client" }

# regular crates
anyhow = "1.0"
base64 = "0.13"
bitflags = "1.2.1"
futures = "0.3"
h2 = { version = "0.3", features = [ "stream" ] }
handlebars = "3.0"
hex = "0.4.3"
http = "0.2"
hyper = { version = "0.14", features = [ "full" ] }
lazy_static = "1.4"
libc = "0.2"
log = "0.4.17"
nix = "0.26.1"
once_cell = "1.3.1"
openssl = "0.10.40"
pam = "0.7"
pam-sys = "0.5"
percent-encoding = "2.1"
pin-project-lite = "0.2"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "1"
syslog = "6.0"
termcolor = "1.1.2"
thiserror = "1.0"
tokio = "1.6"
tokio-openssl = "0.6.1"
tokio-stream = "0.1.0"
tokio-util = { version = "0.7", features = [ "io" ] }
tower-service = "0.3.0"
url = "2.1"
walkdir = "2"
xdg = "2.2"
zstd = { version = "0.12", features = [ "bindgen" ] }
