[package]
name = "pdm"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0"
base64 = "0.13"
lazy_static = "1.4"
yew = { version = "0.21",  features = ["csr"] }
yew-router = { version = "0.18" }
web-sys = { version = "0.3", features = [  "DomRect", "Element", "HtmlDocument", "Selection", "Range"] }
js-sys = "0.3"
log = "0.4.6"
wasm-logger = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "1.0"
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4"
url = "2.1"
percent-encoding = "2.1"
gloo-timers = "0.3"
gettext = "0.4"
regex = "1.5"
futures = { version = "0.3", default-features = false, features = ["std"]}

proxmox-human-byte = "0.1"
proxmox-schema = { version = "3", features = [ "api-types" ]}
proxmox-time = "2"
proxmox-uuid = "1"

pwt = "0.2"
pwt-macros = "0.1"

proxmox-yew-comp = "0.1"

proxmox-login = "0.1"
proxmox-client = "0.4"

pdm-api-types = "0.1"
pdm-client = "0.1"

[patch.crates-io]
pdm-api-types = { path = "../lib/pdm-api-types" }
pdm-client = { path = "../lib/pdm-client" }
proxmox-yew-comp = { path = "../../proxmox-yew-comp" }
pwt = { path = "../../proxmox-yew-widget-toolkit" }
