[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["pwt-assets/scss/crisp-yew-style.scss", "dist/.stage/crisp-yew-style.css"]

[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["pwt-assets/scss/material-yew-style.scss", "dist/.stage/material-yew-style.css"]

[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["pwt-assets/scss/desktop-yew-style.scss", "dist/.stage/desktop-yew-style.css"]
