[serve]
addresses = ["127.0.0.1", "::1"]  # The address to serve on.

# FIXME: enable once trunk doesn't errors out if ignored files do not exist -.-
# https://github.com/trunk-rs/trunk/issues/172
#[watch]
#ignore = [ "*.thanks", "*.mbox", "*.deb", "*.changes", "*.build", "*.buildinfo", "proxmox-datacenter-manager-ui-[0-9]*/" ]

[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["css/crisp-yew-style.scss", "dist/.stage/crisp-yew-style.css"]

[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["css/material-yew-style.scss", "dist/.stage/material-yew-style.css"]

[[hooks]]
stage="build"
command="rust-grass"
command_arguments= ["css/desktop-yew-style.scss", "dist/.stage/desktop-yew-style.css"]
